export const MOTIVATIONAL_QUOTES = [
  { text: "A jornada de mil milhas começa com um único passo.", author: "Lao Tsé" },
  { text: "Não é sobre ter tempo, é sobre criar tempo.", author: null },
  { text: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { text: "Seus sonhos não têm prazo de validade. Respire fundo e continue.", author: null },
  { text: "Disciplina é escolher entre o que você quer agora e o que você mais quer.", author: "Abraham Lincoln" },
  { text: "A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor época é agora.", author: "Provérbio Chinês" },
  { text: "Não espere por circunstâncias ideais. Comece de onde você está.", author: null },
  { text: "O único lugar onde o sucesso vem antes do trabalho é no dicionário.", author: "Vidal Sassoon" },
  { text: "Você não precisa ser perfeito para começar, mas precisa começar para ser perfeito.", author: null },
  { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
  { text: "Acredite que você pode, assim você já está no meio do caminho.", author: "Theodore Roosevelt" },
  { text: "O futuro pertence àqueles que acreditam na beleza de seus sonhos.", author: "Eleanor Roosevelt" },
  { text: "Grandes conquistas são possíveis quando se dá importância aos pequenos começos.", author: null },
  { text: "A motivação nos faz começar. O hábito nos faz continuar.", author: "Jim Ryun" },
  { text: "Você é mais forte do que pensa e vai conseguir mais do que imagina.", author: null },
  { text: "Não deixe que o medo de perder seja maior que a empolgação de vencer.", author: "Robert Kiyosaki" },
  { text: "Cada dia é uma nova oportunidade para mudar sua vida.", author: null },
  { text: "A diferença entre o ordinário e o extraordinário é aquele pequeno extra.", author: "Jimmy Johnson" },
  { text: "O segredo para ir em frente é começar.", author: "Mark Twain" },
  { text: "Sua vida muda quando você decide mudá-la.", author: null },
  { text: "Sonhe grande, comece pequeno, mas comece agora.", author: null },
  { text: "Metas são sonhos com prazo de validade.", author: "Diana Scharf Hunt" },
  { text: "A constância é a mãe do sucesso.", author: null },
  { text: "Não existe elevador para o sucesso. Você precisa subir as escadas.", author: "Zig Ziglar" },
  { text: "Você não falha até desistir de tentar.", author: "Albert Einstein" },
  { text: "O que você planta hoje, colherá amanhã.", author: "Og Mandino" },
  { text: "Sua única limitação é a que você impõe a si mesmo.", author: null },
  { text: "Transforme seus obstáculos em oportunidades.", author: null },
  { text: "A vida é feita de escolhas. Escolha ser feliz.", author: null },
  { text: "Pequenos passos levam a grandes conquistas.", author: null },
  { text: "O planejamento de longo prazo não é pensar em decisões futuras, mas no futuro das decisões presentes.", author: "Peter Drucker" },
  { text: "Não é a força, mas a constância dos bons resultados que conduz os homens à felicidade.", author: "Friedrich Nietzsche" },
  { text: "Onde há vontade, há caminho.", author: null },
  { text: "O maior risco é não correr risco algum.", author: "Mark Zuckerberg" },
  { text: "Sucesso não é final, fracasso não é fatal: é a coragem de continuar que conta.", author: "Winston Churchill" },
  { text: "Não conte os dias, faça os dias contarem.", author: "Muhammad Ali" },
  { text: "A vida começa no fim da sua zona de conforto.", author: null },
  { text: "Você não pode mudar seu passado, mas pode reescrever seu futuro.", author: null },
  { text: "Faça hoje o que outros não querem, viva amanhã como outros não podem.", author: null },
  { text: "Uma pessoa com uma meta clara conquistará mais do que uma sem objetivo.", author: null },
  { text: "Concentre-se no progresso, não na perfeição.", author: null },
  { text: "O impossível é apenas uma opinião.", author: "Paulo Coelho" },
  { text: "Cada manhã traz infinitas possibilidades.", author: null },
  { text: "Sua atitude determina sua direção.", author: null },
  { text: "Não desista. O começo é sempre o mais difícil.", author: null },
  { text: "O segredo do sucesso é a constância do propósito.", author: "Benjamin Disraeli" },
  { text: "Quanto maior a dificuldade, maior a glória.", author: "Cícero" },
  { text: "Nunca é tarde demais para ser o que você poderia ter sido.", author: "George Eliot" },
  { text: "Crie o hábito de alcançar metas.", author: null },
  { text: "A persistência realiza o impossível.", author: null },
];

export function getDailyQuote(): { text: string; author: string | null } {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
  const index = dayOfYear % MOTIVATIONAL_QUOTES.length;
  return MOTIVATIONAL_QUOTES[index];
}
